workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1

    integrations:
      app_store_connect: Codemagic

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: nl.verhuuragenda.app

    scripts:
      - name: Create Flutter project structure
        script: |
          # Save our source code
          cp -r lib lib_backup
          cp pubspec.yaml pubspec_backup.yaml

          # Create fresh Flutter project
          flutter create --org nl.verhuuragenda --project-name verhuuragenda_app .

          # Restore our source code
          rm -rf lib
          mv lib_backup lib
          mv pubspec_backup.yaml pubspec.yaml

          # Update bundle identifier in iOS project
          cd ios
          sed -i '' 's/PRODUCT_BUNDLE_IDENTIFIER = .*/PRODUCT_BUNDLE_IDENTIFIER = nl.verhuuragenda.app;/g' Runner.xcodeproj/project.pbxproj

      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Set up code signing
        script: |
          xcode-project use-profiles

      - name: Build iOS App
        script: |
          flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true

  android-workflow:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      flutter: stable
      java: 17

    scripts:
      - name: Create Flutter project structure
        script: |
          # Save our source code
          cp -r lib lib_backup
          cp pubspec.yaml pubspec_backup.yaml

          # Create fresh Flutter project
          flutter create --org nl.verhuuragenda --project-name verhuuragenda_app .

          # Restore our source code
          rm -rf lib
          mv lib_backup lib
          mv pubspec_backup.yaml pubspec.yaml

      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Build APK
        script: |
          flutter build apk --release

    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
